openapi: 3.0.1
info:
  title: Summits
  description: 'This project provides a domain and wrapper to evaluate backend technologies.
  The domain is just a dummy domain which is coincidentally well known to the author ...'
  contact:
    email: frank.rittinger@virtual-identity.com
  license:
    name: MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Summits on github.
  url: https://github.com/frittinger/summits
tags:
  - name: summit
    description: A mountain summit people like to ascent.
paths:
  /summit/findByHeight:
    get:
      tags:
        - summit
      summary: Finds summits by height.
      description: Summits can be searched for by height. So either all mountains higher or lower then a given height.
      operationId: findSummitsByHeight
      parameters:
        - name: height
          in: query
          description: The minimum or maximum height, currently in meters (could be made configurable in a later phase).
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int64
        - name: rel
          in: query
          description: The relation to the height, either lower or higher
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - higher
              - lower
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Summit'
              examples:
                summit-result-list:
                  $ref: '#/components/examples/summit-result-list'
        400:
          description: Invalid status value
          content: {}
  /summit/findByCountry:
    get:
      tags:
        - summit
      summary: Find all summits of a country.
      description: Currently only the western Alps are supported, i.e. Switzerland, France, etc.
      operationId: findSummitsByCountry
      parameters:
        - name: country
          in: query
          description: Countries to filter by
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Summit'
              examples:
                summit-result-list:
                  $ref: '#/components/examples/summit-result-list'
        400:
          description: Invalid country
          content: {}
  /summit/{summitId}:
    get:
      tags:
        - summit
      summary: Find a summit by ID
      description: Returns a single summit
      operationId: getSummitById
      parameters:
        - name: summitId
          in: path
          description: ID of the summit to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summit'
              examples:
                summit-result:
                  $ref: '#/components/examples/summit-result'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Summit not found
          content: {}
components:
  schemas:
    Summit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Matterhorn
        height:
          type: integer
          format: int32
          description: The height of the summit, currently in meter above sea level
          example: 4482
        country:
          type: string
          description: The country where this summit resides mostly; currently restricted to few countries of the western Alpes
          enum:
            - Switzerland
            - France
            - Italy
            - Austria
            - Germany
  examples:
    summit-result-list:
      value:
        [ {
            id: 1,
            name: Matterhorn,
            height: 4478,
            country: Switzerland
          },
          {
            id: 2,
            name: Mont Blanc,
            height: 4810,
            country: France
          }
        ]
    summit-result:
      value:
        id: 1,
        name: Matterhorn,
        height: 4478,
        country: Switzerland
